apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devsecops-pj-deploy
  labels:
    app: my-devsecops-pj-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-devsecops-pj-deploy
  template:
    metadata:
      labels:
        app: my-devsecops-pj-deploy
    spec:
      containers:
        - name: my-devsecops-pj-app
          image: davismatrix/devsecops-pj:34
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          