apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devsecops-pj-app
  labels:
    app: my-devsecops-pj-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-devsecops-pj-app
  template:
    metadata:
      labels:
        app: my-devsecops-pj-app
    spec:
      containers:
        - name: my-devsecops-pj-app
          image: davismatrix/devsecops-pj:1
          ports:
            - containerPort: 8080