apiVersion: v1
kind: Service
metadata:
  name: my-devsecops-pj-app
  labels:
    app: my-devsecops-pj-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: my-devsecops-pj-app